"""Datos semilla, migrados de src/data/*.js"""

APUNTES = [
    {"id": "apunte-1", "titulo": "Cálculo Diferencial e Integral", "materia": "matematicas", "nivel": "universidad",
     "autor": "Dr. María González", "fecha": "2024-01-15",
     "descripcion": "Apuntes completos de cálculo diferencial e integral con ejemplos prácticos y ejercicios resueltos.",
     "tipo": "pdf", "rating": 4.8, "descargas": 1250, "icono": "fas fa-calculator", "archivo": "calculo.pdf"},
    {"id": "apunte-2", "titulo": "Física Cuántica Básica", "materia": "fisica", "nivel": "universidad",
     "autor": "Prof. Carlos Ruiz", "fecha": "2024-01-10",
     "descripcion": "Introducción a la física cuántica con conceptos fundamentales y aplicaciones modernas.",
     "tipo": "pdf", "rating": 4.6, "descargas": 890, "icono": "fas fa-atom", "archivo": "fisica_cuantica.pdf"},
    {"id": "apunte-3", "titulo": "Química Orgánica - Reacciones", "materia": "quimica", "nivel": "bachillerato",
     "autor": "Dra. Ana Martínez", "fecha": "2024-01-08",
     "descripcion": "Guía completa de reacciones químicas orgánicas con mecanismos detallados.",
     "tipo": "ppt", "rating": 4.7, "descargas": 1100, "icono": "fas fa-flask", "archivo": "quimica_organica.pptx"},
    {"id": "apunte-4", "titulo": "Historia del Arte Renacentista", "materia": "historia", "nivel": "secundaria",
     "autor": "Prof. Luis García", "fecha": "2024-01-05",
     "descripcion": "Análisis detallado del arte renacentista con imágenes y contexto histórico.",
     "tipo": "pdf", "rating": 4.5, "descargas": 650, "icono": "fas fa-palette", "archivo": "arte_renacentista.pdf"},
    {"id": "apunte-5", "titulo": "Literatura Española del Siglo de Oro", "materia": "literatura", "nivel": "bachillerato",
     "autor": "Dra. Carmen López", "fecha": "2024-01-03",
     "descripcion": "Estudio completo de los autores y obras más importantes del Siglo de Oro español.",
     "tipo": "doc", "rating": 4.9, "descargas": 780, "icono": "fas fa-book", "archivo": "siglo_de_oro.docx"},
    {"id": "apunte-6", "titulo": "Gramática Inglesa Avanzada", "materia": "ingles", "nivel": "universidad",
     "autor": "Prof. John Smith", "fecha": "2024-01-01",
     "descripcion": "Gramática inglesa avanzada con ejercicios prácticos y ejemplos de uso.",
     "tipo": "pdf", "rating": 4.4, "descargas": 920, "icono": "fas fa-language", "archivo": "gramatica_inglesa.pdf"},
    {"id": "apunte-7", "titulo": "Biología Celular", "materia": "biologia", "nivel": "universidad",
     "autor": "Dra. Patricia Vega", "fecha": "2023-12-28",
     "descripcion": "Estructura y función de las células con diagramas detallados y explicaciones.",
     "tipo": "pdf", "rating": 4.6, "descargas": 1050, "icono": "fas fa-microscope", "archivo": "biologia_celular.pdf"},
    {"id": "apunte-8", "titulo": "Filosofía Existencialista", "materia": "filosofia", "nivel": "bachillerato",
     "autor": "Prof. Miguel Torres", "fecha": "2023-12-25",
     "descripcion": "Introducción al existencialismo con análisis de los principales filósofos.",
     "tipo": "doc", "rating": 4.3, "descargas": 420, "icono": "fas fa-brain", "archivo": "filosofia_existencialista.docx"},
]

TUTORES = [
    {"id": "tutor-1", "nombre": "Dr. María González", "materia": "matematicas", "nivel": "universidad", "precio": 35,
     "rating": 4.9, "experiencia": "8 años",
     "foto": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
     "biografia": "Doctora en Matemáticas con más de 8 años de experiencia enseñando cálculo, álgebra y estadística.",
     "materias": ["Cálculo", "Álgebra", "Estadística", "Geometría"],
     "disponibilidad": {"lunes": "mañana", "martes": "tarde", "miercoles": "mañana", "jueves": "tarde",
                         "viernes": "mañana", "sabado": "disponible", "domingo": "no disponible"},
     "idiomas": ["español", "ingles"],
     "resenas": [{"autor": "Carlos M.", "rating": 5, "texto": "Excelente profesora, muy clara en sus explicaciones."},
                 {"autor": "Ana L.", "rating": 5, "texto": "Me ayudó mucho con cálculo diferencial."},
                 {"autor": "Pedro R.", "rating": 4, "texto": "Muy paciente y dedicada."}]},
    {"id": "tutor-2", "nombre": "Prof. Carlos Ruiz", "materia": "fisica", "nivel": "bachillerato", "precio": 25,
     "rating": 4.7, "experiencia": "5 años",
     "foto": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
     "biografia": "Ingeniero Físico con amplia experiencia en enseñanza de física a nivel bachillerato.",
     "materias": ["Física", "Mecánica", "Termodinámica", "Óptica"],
     "disponibilidad": {"lunes": "tarde", "martes": "mañana", "miercoles": "tarde", "jueves": "mañana",
                         "viernes": "tarde", "sabado": "disponible", "domingo": "disponible"},
     "idiomas": ["español"],
     "resenas": [{"autor": "Laura S.", "rating": 5, "texto": "Muy bueno explicando conceptos difíciles."},
                 {"autor": "Miguel T.", "rating": 4, "texto": "Clases muy dinámicas y entretenidas."}]},
    {"id": "tutor-3", "nombre": "Dra. Ana Martínez", "materia": "quimica", "nivel": "universidad", "precio": 30,
     "rating": 4.8, "experiencia": "6 años",
     "foto": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
     "biografia": "Doctora en Química Orgánica con experiencia en investigación y docencia universitaria.",
     "materias": ["Química Orgánica", "Bioquímica", "Química Inorgánica", "Fisicoquímica"],
     "disponibilidad": {"lunes": "mañana", "martes": "no disponible", "miercoles": "mañana", "jueves": "tarde",
                         "viernes": "mañana", "sabado": "no disponible", "domingo": "no disponible"},
     "idiomas": ["español", "ingles"],
     "resenas": [{"autor": "Roberto V.", "rating": 5, "texto": "Increíble profesora, muy detallada."},
                 {"autor": "Sofia C.", "rating": 5, "texto": "Me salvó en química orgánica."}]},
    {"id": "tutor-4", "nombre": "Prof. Luis García", "materia": "historia", "nivel": "secundaria", "precio": 20,
     "rating": 4.6, "experiencia": "4 años",
     "foto": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
     "biografia": "Licenciado en Historia con especialización en historia universal y arte.",
     "materias": ["Historia Universal", "Historia del Arte", "Geografía", "Ciencias Sociales"],
     "disponibilidad": {"lunes": "tarde", "martes": "tarde", "miercoles": "tarde", "jueves": "tarde",
                         "viernes": "tarde", "sabado": "disponible", "domingo": "disponible"},
     "idiomas": ["español"],
     "resenas": [{"autor": "Elena P.", "rating": 4, "texto": "Muy interesante, hace la historia divertida."},
                 {"autor": "Diego M.", "rating": 5, "texto": "Excelente profesor, muy preparado."}]},
    {"id": "tutor-5", "nombre": "Dra. Carmen López", "materia": "literatura", "nivel": "bachillerato", "precio": 28,
     "rating": 4.9, "experiencia": "7 años",
     "foto": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
     "biografia": "Doctora en Literatura Española con amplia experiencia en análisis literario y redacción.",
     "materias": ["Literatura Española", "Redacción", "Análisis Literario", "Lingüística"],
     "disponibilidad": {"lunes": "mañana", "martes": "mañana", "miercoles": "no disponible", "jueves": "mañana",
                         "viernes": "mañana", "sabado": "disponible", "domingo": "no disponible"},
     "idiomas": ["español", "frances"],
     "resenas": [{"autor": "Isabel R.", "rating": 5, "texto": "Mejor profesora de literatura que he tenido."},
                 {"autor": "Antonio G.", "rating": 5, "texto": "Muy buena para análisis de textos."}]},
    {"id": "tutor-6", "nombre": "Prof. John Smith", "materia": "ingles", "nivel": "universidad", "precio": 40,
     "rating": 4.8, "experiencia": "10 años",
     "foto": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
     "biografia": "Nativo inglés con certificación TESOL y más de 10 años de experiencia enseñando inglés.",
     "materias": ["Inglés Conversacional", "TOEFL", "IELTS", "Business English"],
     "disponibilidad": {"lunes": "disponible", "martes": "disponible", "miercoles": "disponible",
                         "jueves": "disponible", "viernes": "disponible", "sabado": "disponible", "domingo": "disponible"},
     "idiomas": ["ingles", "español"],
     "resenas": [{"autor": "María F.", "rating": 5, "texto": "Nativo perfecto, muy profesional."},
                 {"autor": "Carlos D.", "rating": 4, "texto": "Excelente para preparar TOEFL."}]},
    {"id": "tutor-7", "nombre": "Dra. Patricia Vega", "materia": "biologia", "nivel": "universidad", "precio": 32,
     "rating": 4.7, "experiencia": "6 años",
     "foto": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
     "biografia": "Doctora en Biología Molecular con experiencia en investigación y docencia.",
     "materias": ["Biología Celular", "Genética", "Microbiología", "Ecología"],
     "disponibilidad": {"lunes": "tarde", "martes": "mañana", "miercoles": "tarde", "jueves": "mañana",
                         "viernes": "tarde", "sabado": "no disponible", "domingo": "no disponible"},
     "idiomas": ["español", "ingles"],
     "resenas": [{"autor": "Alejandro H.", "rating": 5, "texto": "Muy clara en sus explicaciones de biología."},
                 {"autor": "Valeria M.", "rating": 4, "texto": "Excelente para genética."}]},
    {"id": "tutor-8", "nombre": "Prof. Miguel Torres", "materia": "filosofia", "nivel": "bachillerato", "precio": 22,
     "rating": 4.5, "experiencia": "3 años",
     "foto": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
     "biografia": "Licenciado en Filosofía con especialización en filosofía moderna y ética.",
     "materias": ["Filosofía Moderna", "Ética", "Lógica", "Historia de la Filosofía"],
     "disponibilidad": {"lunes": "noche", "martes": "noche", "miercoles": "noche", "jueves": "noche",
                         "viernes": "noche", "sabado": "disponible", "domingo": "disponible"},
     "idiomas": ["español"],
     "resenas": [{"autor": "Gabriel L.", "rating": 4, "texto": "Muy bueno para entender conceptos filosóficos."},
                 {"autor": "Natalia K.", "rating": 5, "texto": "Hace la filosofía muy interesante."}]},
]

POSTS = [
    {"id": "post-1", "titulo": "¿Cómo resolver ecuaciones cuadráticas por factorización?",
     "contenido": "Estoy teniendo problemas para entender cómo factorizar ecuaciones cuadráticas. ¿Alguien puede explicarme el proceso paso a paso con ejemplos?",
     "autor": "Carlos M.", "fecha": "2024-01-15", "nivel": "secundaria", "materia": "matematicas", "tipo": "pregunta",
     "tags": ["ecuaciones", "factorización", "álgebra"], "votos": 12, "respuestas": 2, "vistas": 156, "resuelto": False,
     "responses": [
         {"id": "resp-1", "autor": "Prof. María G.", "fecha": "2024-01-15",
          "texto": "Para factorizar, primero identifica dos números que multiplicados den el término independiente y sumados el coeficiente del término lineal."},
         {"id": "resp-2", "autor": "Ana S.", "fecha": "2024-01-15",
          "texto": "Recuerda verificar la respuesta sustituyendo en la ecuación original."}]},
    {"id": "post-2", "titulo": "Debate: ¿Es mejor estudiar en grupo o individualmente?",
     "contenido": "Quiero conocer sus opiniones sobre los pros y contras de estudiar en grupo versus estudiar solo.",
     "autor": "Ana L.", "fecha": "2024-01-14", "nivel": "universidad", "materia": "general", "tipo": "debate",
     "tags": ["estudio", "métodos", "productividad"], "votos": 25, "respuestas": 3, "vistas": 234, "resuelto": False,
     "responses": [
         {"id": "resp-3", "autor": "Luis P.", "fecha": "2024-01-14",
          "texto": "Depende del tema. Para materias teóricas prefiero estudiar solo, pero para ejercicios me sirve el grupo."},
         {"id": "resp-4", "autor": "María T.", "fecha": "2024-01-14",
          "texto": "El grupo ayuda a mantener la motivación, aunque es más difícil coordinar horarios."},
         {"id": "resp-5", "autor": "Jorge R.", "fecha": "2024-01-14",
          "texto": "Combinando ambos métodos obtengo mejores resultados."}]},
    {"id": "post-3", "titulo": "Recursos útiles para aprender Física Cuántica",
     "contenido": "Comparto una lista de recursos que me han ayudado mucho en mi curso de física cuántica.",
     "autor": "Prof. Miguel T.", "fecha": "2024-01-13", "nivel": "universidad", "materia": "fisica", "tipo": "recurso",
     "tags": ["física cuántica", "recursos", "libros"], "votos": 18, "respuestas": 1, "vistas": 189, "resuelto": False,
     "responses": [{"id": "resp-6", "autor": "Laura Z.", "fecha": "2024-01-13",
                    "texto": "¡Gracias! Agregaría el canal de Quantum Crash Course en YouTube."}]},
    {"id": "post-4", "titulo": "Anuncio: Nuevo grupo de estudio de Química Orgánica",
     "contenido": "Estoy formando un grupo de estudio para química orgánica. Nos reuniremos los martes y jueves a las 7 PM.",
     "autor": "Dra. Patricia V.", "fecha": "2024-01-12", "nivel": "universidad", "materia": "quimica", "tipo": "anuncio",
     "tags": ["grupo de estudio", "química orgánica", "reuniones"], "votos": 7, "respuestas": 0, "vistas": 98,
     "resuelto": False, "responses": []},
    {"id": "post-5", "titulo": "¿Cuál es la diferencia entre mitosis y meiosis?",
     "contenido": "Necesito ayuda para entender las diferencias principales entre mitosis y meiosis.",
     "autor": "Laura S.", "fecha": "2024-01-11", "nivel": "bachillerato", "materia": "biologia", "tipo": "pregunta",
     "tags": ["mitosis", "meiosis", "división celular"], "votos": 9, "respuestas": 2, "vistas": 127, "resuelto": True,
     "responses": [
         {"id": "resp-7", "autor": "Dra. Patricia V.", "fecha": "2024-01-11",
          "texto": "La mitosis genera dos células hijas idénticas, mientras que la meiosis produce cuatro células con la mitad del material genético."},
         {"id": "resp-8", "autor": "Diego R.", "fecha": "2024-01-11",
          "texto": "En meiosis existen dos divisiones consecutivas y ocurre recombinación genética."}]},
    {"id": "post-6", "titulo": "Técnicas de memorización para Historia",
     "contenido": "Comparto algunas técnicas que uso para memorizar fechas y eventos históricos.",
     "autor": "Diego R.", "fecha": "2024-01-10", "nivel": "secundaria", "materia": "historia", "tipo": "recurso",
     "tags": ["memorización", "historia", "técnicas"], "votos": 14, "respuestas": 1, "vistas": 145, "resuelto": False,
     "responses": [{"id": "resp-9", "autor": "Sofia C.", "fecha": "2024-01-10",
                    "texto": "El uso de líneas de tiempo visuales también ayuda muchísimo."}]},
    {"id": "post-7", "titulo": "¿Cómo mejorar mi comprensión lectora en Literatura?",
     "contenido": "Tengo dificultades para entender textos literarios complejos.",
     "autor": "Sofia C.", "fecha": "2024-01-09", "nivel": "bachillerato", "materia": "literatura", "tipo": "pregunta",
     "tags": ["comprensión lectora", "literatura", "estrategias"], "votos": 11, "respuestas": 2, "vistas": 167,
     "resuelto": False, "responses": [
         {"id": "resp-10", "autor": "Dra. Carmen L.", "fecha": "2024-01-09",
          "texto": "Lee dos veces el texto, la primera para entender la trama y la segunda para analizar recursos literarios."},
         {"id": "resp-11", "autor": "Marcos Q.", "fecha": "2024-01-09",
          "texto": "Subraya conceptos clave y escribe resúmenes cortos por capítulo."}]},
    {"id": "post-8", "titulo": "Debate: ¿Debería ser obligatorio el inglés en la universidad?",
     "contenido": "¿Qué opinan sobre hacer obligatorio el inglés en todas las carreras universitarias?",
     "autor": "Roberto V.", "fecha": "2024-01-08", "nivel": "universidad", "materia": "ingles", "tipo": "debate",
     "tags": ["inglés", "universidad", "obligatorio"], "votos": 22, "respuestas": 2, "vistas": 298, "resuelto": False,
     "responses": [
         {"id": "resp-12", "autor": "John S.", "fecha": "2024-01-08",
          "texto": "El inglés abre puertas profesionales, debería haber al menos un nivel básico obligatorio."},
         {"id": "resp-13", "autor": "Lucía P.", "fecha": "2024-01-08",
          "texto": "Podría ser opcional pero con incentivos para quienes lo completen."}]},
]
